use_frameworks!

platform :ios, '8.0'

target 'WKURLSchemeHandlerDemo_Example' do
  pod 'WKURLSchemeHandlerDemo', :path => '../'

  target 'WKURLSchemeHandlerDemo_Tests' do
    inherit! :search_paths

    
  end
end
